services:
- type: web
  name: rabbitmq
  env: docker
  envVars:
  - key: RABBITMQ_A_R_Y
    generateValue: true
  - key: RABBITMQ_TICKETER
    value: rabbitmq
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: true
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10
